export const demoCategories = [
  {
    id: "demo-dogs",
    name: "Dogs",
    slug: "dogs",
    path: "/dogs",
    intro: "For walks, road trips, and everything in between.",
    parentId: null,
  },
  {
    id: "demo-cats",
    name: "Cats",
    slug: "cats",
    path: "/cats",
    intro: "Everyday comforts for your curious companion.",
    parentId: null,
  },
  {
    id: "demo-harnesses",
    name: "Harnesses",
    slug: "harnesses",
    path: "/dogs/harnesses",
    intro: "Find a comfortable fit for your next adventure.",
    parentId: "demo-dogs",
  },
  {
    id: "demo-leashes",
    name: "Leashes",
    slug: "leashes",
    path: "/dogs/leashes",
    intro: "A little freedom. A dependable connection.",
    parentId: "demo-dogs",
  },
  {
    id: "demo-clothing",
    name: "Clothing",
    slug: "clothing",
    path: "/dogs/clothing",
    intro: "Comfortable layers for cooler days.",
    parentId: "demo-dogs",
  },
  {
    id: "demo-paws",
    name: "Paw protection",
    slug: "paw-protection",
    path: "/dogs/paw-protection",
    intro: "Thoughtful essentials for busy paws.",
    parentId: "demo-dogs",
  },
  {
    id: "demo-car",
    name: "Car safety",
    slug: "car-safety",
    path: "/dogs/car-safety",
    intro: "Plan for calmer, more comfortable trips.",
    parentId: "demo-dogs",
  },
];
export const demoBrands = [
  {
    id: "demo-trail",
    name: "Trail & Tail",
    slug: "trail-and-tail",
    description: "Fictional development brand for outdoor essentials.",
  },
  {
    id: "demo-soft",
    name: "Softpaw Studio",
    slug: "softpaw-studio",
    description: "Fictional development brand for everyday comfort.",
  },
  {
    id: "demo-whisker",
    name: "Whisker & Co.",
    slug: "whisker-and-co",
    description: "Fictional development brand for feline enrichment.",
  },
];
const specs = [
  [
    "Everyday adventure harness",
    "everyday-adventure-harness",
    "harness",
    34,
    "demo-harnesses",
    "demo-trail",
    "Thoughtfully designed for everyday walks.",
  ],
  [
    "Weekend rope leash",
    "weekend-rope-leash",
    "leash",
    22,
    "demo-leashes",
    "demo-trail",
    "A comfortable connection for your next walk.",
  ],
  [
    "Cozy club dog hoodie",
    "cozy-club-dog-hoodie",
    "hoodie",
    29,
    "demo-clothing",
    "demo-soft",
    "A soft extra layer for crisp mornings.",
  ],
  [
    "Gentle grip dog socks",
    "gentle-grip-dog-socks",
    "socks",
    18,
    "demo-paws",
    "demo-soft",
    "Soft indoor socks for everyday comfort.",
  ],
  [
    "Window watch cat perch",
    "window-watch-cat-perch",
    "bed",
    48,
    "demo-cats",
    "demo-whisker",
    "A comfortable spot to watch the world.",
  ],
  [
    "Road companion travel mat",
    "road-companion-travel-mat",
    "bed",
    39,
    "demo-car",
    "demo-trail",
    "A familiar resting spot away from home.",
  ],
  [
    "Curious cat play wand",
    "curious-cat-play-wand",
    "leash",
    12,
    "demo-cats",
    "demo-whisker",
    "Make time for supervised play together.",
  ],
  [
    "All-season paw balm",
    "all-season-paw-balm",
    "balm",
    16,
    "demo-paws",
    "demo-soft",
    "A simple addition to your paw care routine.",
  ],
];
export const demoProducts = specs.map((s, i) => ({
  id: "demo-product-" + i,
  title: s[0] as string,
  slug: s[1] as string,
  mainImage: `/images/product-${s[2]}.svg`,
  imageAlt: s[0] as string,
  price: s[3] as number,
  oldPrice: null,
  rating: null,
  reviewCount: null,
  brandId: s[5] as string,
  brand: demoBrands.find((b) => b.id === s[5])!,
  categories: [
    { category: demoCategories.find((c) => c.id === s[4])!, primary: true },
  ],
  shortDescription: s[6] as string,
  description:
    "This is a fictional development product. Replace it with a verified product, licensed imagery, and your saved affiliate link before publishing.",
  features: [
    "Development example — specifications must be verified",
    "Check sizing and care instructions with the merchant",
  ],
  pros: [],
  cons: [],
  bestFor: "",
  notIdealFor: "",
  currency: "USD",
  status: "PUBLISHED",
  featured: i < 4,
  merchant: "Demo merchant",
  affiliateUrl: "https://example.com/?affiliate=development&product=" + i,
  buttonText: "Shop Now",
  openNewTab: true,
  trackClicks: true,
  affiliateDisclosure: "",
  isDemo: true,
  images: [],
  seo: {},
  aeo: {},
  badge: i === 0 ? "Editor’s selection" : null,
  createdAt: new Date("2026-01-01"),
  updatedAt: new Date("2026-01-01"),
  publishedAt: new Date("2026-01-01"),
}));
export const demoContent = [
  {
    id: "demo-guide",
    type: "BUYING_GUIDE",
    slug: "choosing-an-everyday-dog-harness",
    title: "Find the right harness for your daily walks",
    excerpt:
      "Fit, comfort, and practical details to consider before choosing a harness.",
    species: "dogs",
    image: "/images/guide-walk.svg",
    imageAlt: "Illustration of a daily dog walk",
    blocks: [
      {
        type: "paragraph",
        text: "Start with your dog’s measurements and the manufacturer’s sizing guide. A harness should allow comfortable movement and should not rub behind the front legs.",
      },
      { type: "h2", text: "What to compare" },
      {
        type: "list",
        items: [
          "Measurement and adjustability",
          "Attachment points and handling",
          "Materials and care instructions",
        ],
      },
      {
        type: "product",
        productId: "demo-product-0",
        label: "Development product example",
      },
    ],
    aeo: {
      directAnswer:
        "Choose a harness using your dog’s measurements, then check adjustability, comfort, and the manufacturer’s instructions.",
    },
    seo: {},
    specialized: {},
    status: "PUBLISHED",
    author: null,
    reviewer: null,
    reviewedAt: null,
    emergencyWarning: "",
    disclaimer: "",
    sources: [],
    faqs: [],
    products: [{ product: demoProducts[0] }],
    categories: [],
    relatedFrom: [],
    updatedAt: new Date("2026-01-01"),
    publishedAt: new Date("2026-01-01"),
  },
  {
    id: "demo-blog",
    type: "BLOG",
    slug: "a-better-everyday-walk",
    title: "Small ways to make your everyday walk better",
    excerpt: "Bring a little more curiosity to your time outdoors together.",
    species: "dogs",
    image: "/images/guide-walk.svg",
    imageAlt: "Outdoor walk illustration",
    blocks: [
      {
        type: "paragraph",
        text: "Leave time for your dog to explore at a comfortable pace. Prepare water, check your walking gear, and choose a route that suits the weather and your companion.",
      },
    ],
    aeo: {},
    seo: {},
    specialized: {},
    status: "PUBLISHED",
    author: null,
    reviewer: null,
    reviewedAt: null,
    emergencyWarning: "",
    disclaimer: "",
    sources: [],
    faqs: [],
    products: [],
    categories: [],
    relatedFrom: [],
    updatedAt: new Date("2026-01-01"),
    publishedAt: new Date("2026-01-01"),
  },
];
export const defaultSettings = {
  demoMode: true,
  logo: "",
  favicon: "",
  defaultSocialImage: "",
  defaultAuthorId: "",
  siteName: "Petsmartinn",
  contactEmail: "",
  organizationName: "Petsmartinn",
  defaultTitle: "Petsmartinn | Good things for your best friend",
  defaultDescription:
    "Discover thoughtful pet essentials, practical buying guides, and advice for happier days together.",
  affiliateDisclosure:
    "As an Amazon Associate I earn from qualifying purchases. We may earn a commission when you buy through links on this site.",
  heroTitle: "Good things.\nFor your best friend.",
  heroSubtitle:
    "Thoughtful essentials, helpful guides, and a little more joy in every day together.",
  heroButtonText: "Explore dog essentials",
  heroButtonUrl: "/dogs",
  heroImage: "/images/hero-dog.svg",
  featuredProductIds: [] as string[],
  featuredCategoryIds: [] as string[],
  featuredBrandIds: [] as string[],
  featuredContentIds: [] as string[],
  sectionOrder: [
    "pets",
    "categories",
    "products",
    "brands",
    "guides",
    "advice",
    "newsletter",
  ],
  hiddenSections: [] as string[],
  footerText: "A little care. A lot of love.",
  socialProfiles: {},
  googleAnalyticsId: "",
  searchConsoleVerification: "",
  defaultMedicalDisclaimer:
    "This information is educational and does not replace individual veterinary advice.",
};
